### ISSUE TITLE
how i fix this issue

### ISSUE THREAD

**Issue by SafeRhino** [jjmerri/fifty-fifty-token#2]
Warning: Contract code size exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries. --> yy.sol:778:1: | 778 | contract FiftyFiftyToken is Context, IERC20, Ownable { | ^ (Relevant source part starts here and spans across multiple lines).

**Comment by jjmerri** [comment]
Did you try enabling the optimizer?

**Comment by SafeRhino** [comment]
no

**Comment by SafeRhino** [comment]
thanks bro its work now .
https://fiftyfiftytoken.com/
is this yous token?

**Comment by jjmerri** [comment]
awesome! Yup, that is my token!
